server:
  port: 8082
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/igrsmain
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
     jdbc.initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  security:
    user:
       name: preeti
       password: 12345
  application:
    name: MAIL-SERVICE
  devtools:
    restart:
      enabled: true
      
  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
       
  
#For Remove timeeout error on server     
  ribbon: 
     ConnectTimeout: 3000
     ReadTimeout: 60000      
       
eureka:
  instance:
    prefer-ip-address: false
  client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://192.168.1.60:8761/eureka       

   
        
       

       

  
                                  
   